version: '3'
name: renda_gestor

services:
  mysql:
    image: docker.io/bitnami/mysql:8.2
    ports:
      - '3306:3306'
    networks:
      - app-tier
    volumes:
      - 'mysql_data:/bitnami/mysql/data'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    healthcheck:
      test: ['CMD', '/opt/bitnami/scripts/mysql/healthcheck.sh']
      interval: 15s
      timeout: 5s
      retries: 6

networks:
  app-tier:
    driver: bridge

volumes:
  mysql_data:
    driver: local
